### ISSUE TITLE
关于教师模型设置的问题

### ISSUE THREAD

**Issue by Hugo-cell111** [ZhenZHAO/iMAS#14]
[您好！我在实现自己的代码时，也遇到了U2PL一样的问题（详见此[链接](https://github.com/Haochen-Wang409/U2PL/issues/64)），即如果把教师模型设置为eval模式，掉点会很严重，所以不得不设置为train模式。但是我看到您这份代码把教师模型设置为eval模式，performance也很不错。想问一下您觉得把教师模型设置为eval模式会掉点的原因是什么？

**Comment by ZhenZHAO** [comment]
我应该一直用是的eval()吧?  包括另一份工作，https://github.com/ZhenZHAO/AugSeg， 也是eval()。(BTW, 这工作更简洁，性能看着也更好，，怪没有好好调imas) 。如果我没记错，imas和augseg，修改eval 和train 并不会太影响性能。

至于您代码里掉点原因呢？应该在于teacher BN的处理上。因为teacher 的权重是ema更新的，那么eval, train的主要差别就在BN上了。

**Comment by Hugo-cell111** [comment]
噢我知道了，原来您除了update模型参数，还update了BN的参数，应该是这行[代码](https://github.com/ZhenZHAO/AugSeg/blob/main/train_semi.py#L410)，然后U2PL它如果只设置了eval模式，没有同步更新BN参数，那效果就很差。原因弄清楚了，谢谢！

**Comment by Hugo-cell111** [comment]
您好！另外想问一下你们更新教师模型的BN参数时，有参考CVPR2022年EMAN的论文吗？如果不更新教师模型的BN参数，直接设置为eval模式，效果是不是就变很差了？

**Comment by ZhenZHAO** [comment]
- “EMAN”？？ 文章链接发一下？
- 
- "如果不更新教师模型的BN参数，直接设置为eval模式，效果是不是就变很差了？" 这个你跑跑试试看，我已经不太记得了。BN的问题，其实我之前做半监督分类，其实没有太大影响，而且因为strong aug能拓宽分不的原因，我之前一直把student的bn直接copy给teacher的。我看我这几个分割的代码里仍然这么写过，后来都comment掉了。。你都可以试试呢，跑实验观察一下

**Comment by ZhenZHAO** [comment]
哦对，ICCV21 还有个可分离的BN （叫simplebaseline？？），DA里面常见的一种玩法，你也可以试试看

**Comment by ZhenZHAO** [comment]
哎呦，，之前有人问过我同样的问题，refer to https://github.com/ZhenZHAO/AugSeg/issues/4

**Comment by Hugo-cell111** [comment]
请问有论文链接吗？谢谢！









 
 
 ----------回复的邮件信息----------
 Zhen ***@***.***&gt; 于2023年9月22日(周五) 下午4:02写道:

  

 
哦对，ICCV21 还有个可分离的BN （叫simplebaseline？？），DA里面常见的一种玩法，你也可以试试看

**Comment by Hugo-cell111** [comment]
EMAN的链接：https://blog.csdn.net/weixin_51697828/article/list/

 
 
 ----------回复的邮件信息----------
 Zhen ***@***.***&gt; 于2023年9月22日(周五) 下午4:02写道:

  

 
哦对，ICCV21 还有个可分离的BN （叫simplebaseline？？），DA里面常见的一种玩法，你也可以试试看

**Comment by ZhenZHAO** [comment]
jianlong yuan, "A Simple Baseline for Semi-supervised Semantic Segmentation with Strong Data Augmentation",Iccv 21




发自我的手机


-------- 原始邮件 --------
发件人： Mr_Go_is_surfing ***@***.***>
日期： 2023年9月22日周五 下午4:11
收件人： ZhenZHAO/iMAS ***@***.***>
抄送： Zhen ZHAO ***@***.***>, Comment ***@***.***>
主 题： Re: [ZhenZHAO/iMAS] 关于教师模型设置的问题 (Issue #14)

请问有论文链接吗？谢谢！











----------回复的邮件信息----------
Zhen ***@***.***&gt; 于2023年9月22日(周五) 下午4:02写道:




哦对，ICCV21 还有个可分离的BN （叫simplebaseline？？），DA里面常见的一种玩法，你也可以试试看

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

―

**Comment by ZhenZHAO** [comment]
这文章我们后面看到了，也讨论了。因为不是分割也没那么留意，我最初应该是在psmt这个代码里看的ema一下bn，就follow下来了。主要也是在半监督分类里，玩bn并没有太大影响，但是对分割倒是影响挺大。当然还可以再简单直接的，再过一次weak，但对应的，aug也应该调。cvpr23周期里，我还玩一个工作，refer to
https://github.com/ZhenZHAO/DPMS。这里我记得是聊了一下稳定bn，稳定weight。可以去那个里开issue聊。

实验我从上一年cvpr之后就很少跑了，效果啥的，你跑跑实验试试看。


发自我的手机


-------- 原始邮件 --------
发件人： Mr_Go_is_surfing ***@***.***>
日期： 2023年9月22日周五 下午4:14
收件人： ZhenZHAO/iMAS ***@***.***>
抄送： Zhen ZHAO ***@***.***>, Comment ***@***.***>
主 题： Re: [ZhenZHAO/iMAS] 关于教师模型设置的问题 (Issue #14)

EMAN的链接：https://blog.csdn.net/weixin_51697828/article/list/



----------回复的邮件信息----------
Zhen ***@***.***&gt; 于2023年9月22日(周五) 下午4:02写道:




哦对，ICCV21 还有个可分离的BN （叫simplebaseline？？），DA里面常见的一种玩法，你也可以试试看

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

―
